#!/usr/bin/env python3
"""Build the self-hosted app (docs/index.html) from the shared app source (index.html).

index.html is published as-is to claude.ai, which wraps it in a document skeleton.
For GitHub Pages we add that skeleton ourselves, plus the local runtime (docs/local.js)
that replaces claude.ai storage and photo reading with free on-device versions.
Run after every change to index.html:  python3 tools/build_docs.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
app = (ROOT / "index.html").read_text()

head = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#1f5f73">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Warehouse">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icon-180.png">
<link rel="icon" href="icon-180.png">
<style>
:root { color-scheme: light; padding-top: env(safe-area-inset-top, 0px); padding-bottom: env(safe-area-inset-bottom, 0px); }
body { margin: 0; font: 14px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; background: #f7f7f5; }
img { max-width: 100%; }
[hidden] { display: none !important; }
</style>
<script src="cloud-config.js"></script>
<script src="local.js"></script>
</head>
<body>
<!-- Generated by tools/build_docs.py from ../index.html. Edit index.html, then rebuild. -->
"""
(ROOT / "docs" / "index.html").write_text(head + app + "\n</body>\n</html>\n")
print("wrote docs/index.html")
